### ISSUE TITLE
replace parsing_errors lists with logging

### ISSUE THREAD

**Issue by mscarey** [scrapd/scrapd#185]
Issue Type
----------

- Feature request

Current Behavior
----------------

It's hard to use and document some functions because they return tuples including the errors they generated in addition to their "real" return values.

Expected Behavior
-----------------

Errors and debug messages don't need to be passed as return values from functions, especially when the function returned a useable value.

Possible Solution
-----------------

Only use the `logging` module or the `loguru` import to log errors and debugging messages. 

Steps to Reproduce
------------------

1.
2.
3.

Context
-------

**Comment by rgreinho** [comment]
That's how it was before and it was making things too difficult to spot the errors and the right things to fix. So we had to go away from it.

This design decision was made in order to simplify the debugging.  No the output is clearer, spotting the problems is faster, hence fixing it.

We are not reverting.
