### ISSUE TITLE
Remove duplicate entries

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapd#48]
Issue Type
----------

- Feature request

Current Behavior
----------------

Some entries are duplicated because they are published several times (the police may some times need to update the information and creates a new entry).

For instance:
```json
$ scrapd --format json --from "Jan 1 2018" --to "Jan 10 2018"
[
  {
    "Age": 23,
    "Case": "18-0041689",
    "DOB": "11-27-94)",
    "Date": "Thursday, January 4, 2018",
    "Ethnicity": "Hispanic",
    "Fatal crashes this year": "1",
    "First Name": "Ashley",
    "Gender": "female",
    "Last Name": "Martinez",
    "Link": "http://austintexas.gov/news/traffic-fatality-1-3",
    "Location": "5600 N IH 35 Northbound",
    "Notes": "Eloy Herrera, Hispanic male (D.O.B. 4-9-02)",
    "Time": "11:57 p.m."
  },
  {
    "Case": "18-0041689",
    "Date": "Thursday, January 4, 2018",
    "Fatal crashes this year": "1",
    "Link": "http://austintexas.gov/news/traffic-fatality-1-2",
    "Location": "5600 N IH 35 Northbound",
    "Time": "11:57 p.m."
  }
]
```

Expected Behavior
-----------------

Entries like that should be combined, or the least recent entry discarded.

**Comment by mrengler** [comment]
I have a branch that's nearly ready for PR, but I can't figure out how the ensure_results() test in test_retrieve works. With duplicate cases removed, there should actually be 72 entries over that time period instead of 74, but since I'm not sure where the 74 is computed / input, I haven't altered the test so it fails.

**Comment by rgreinho** [comment]
There were **73 fatalities in 2018** https://austintexas.gov/news/traffic-fatality-73-2. The first one has a duplicate (https://austintexas.gov/news/traffic-fatality-1-2 // https://austintexas.gov/news/traffic-fatality-1-3), that is why we end up with 74 entries.

To update the integration tests, simply update the feature test file :https://github.com/scrapd/scrapd/blob/master/tests/features/retrieve.feature#L14. If you are not familiar with Behavior Driven Development, there is a great series of blog post on the automation panda blog: https://automationpanda.com/bdd/

As a side note, nou can still create a PR even though you are still working it, just mention it is still a work in progress (WIP) in the comment.

**Comment by mrengler** [comment]
Thanks! I figured out the other duplicate found:

[http://austintexas.gov/news/traffic-fatality-54-3](http://austintexas.gov/news/traffic-fatality-54-3)
[http://austintexas.gov/news/traffic-fatality-55-suspect-vehicle-video](http://austintexas.gov/news/traffic-fatality-55-suspect-vehicle-video)

In the second link, fatality 54 is incorrectly referred to as fatality 55, which is actually a separate case. But since the case numbers on these pages are the same, the entries are combined.

Thanks for those! I will read up and open a WIP PR.

**Comment by rgreinho** [comment]
Woow good finding Detective @mrengler! This one was even trickier as they have different fatality numbers!

**Comment by rgreinho** [comment]
Fixed.
